#!/bin/bash
#
# Renders all deployment-specific config into this (otherwise generic) repo from
# the sibling watermeter-config repo. Every generated file is gitignored, so this
# repo itself contains no deployment-specific values and can be forked/deployed
# by anyone who supplies their own watermeter-config.
#
# Generates:
#   .firebaserc              <- projectId          (firebase CLI target)
#   pwa/firebase-config.js   <- web config + VAPID  (public client identifiers)
#   firestore.rules          <- allowed emails      (rendered into the template)
#
# Run this before `firebase deploy`.

set -e

# start in the repo root (this script lives in dev/)
cd "$(dirname "$0")/.."

CONFIG_DIR="../watermeter-config/config/firebase"
WEB_CONFIG="$CONFIG_DIR/web-config.json"
EMAILS_FILE="$CONFIG_DIR/allowed-emails.json"

for f in "$WEB_CONFIG" "$EMAILS_FILE"; do
    if [[ ! -f "$f" ]]; then
        echo "Missing $f -- is watermeter-config cloned next to this repo?" >&2
        exit 1
    fi
done

mkdir -p pwa

# .firebaserc (project id)
node -e '
  const fs = require("fs");
  const c = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
  fs.writeFileSync(".firebaserc",
    JSON.stringify({ projects: { default: c.projectId } }, null, 2) + "\n");
' "$WEB_CONFIG"

# pwa/firebase-config.js (public web config + VAPID key)
node -e '
  const fs = require("fs");
  const c = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
  const out =
    "// GENERATED by dev/render-config.sh from watermeter-config. Do not edit.\n" +
    "// These values are public client-side identifiers, not secrets.\n\n" +
    "export const firebaseConfig = " + JSON.stringify(c.web, null, 2) + ";\n\n" +
    "export const vapidKey = " + JSON.stringify(c.vapidKey) + ";\n";
  fs.writeFileSync("pwa/firebase-config.js", out);
' "$WEB_CONFIG"

# firestore.rules (allowed emails injected into the template)
EMAILS=$(node -e '
  const fs = require("fs");
  const list = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
  process.stdout.write(list.map(e => JSON.stringify(e)).join(", "));
' "$EMAILS_FILE")

node -e '
  const fs = require("fs");
  const tpl = fs.readFileSync("firestore.rules.template", "utf8");
  if (!tpl.includes("__ALLOWED_EMAILS__")) {
    console.error("template is missing the __ALLOWED_EMAILS__ placeholder");
    process.exit(1);
  }
  fs.writeFileSync("firestore.rules", tpl.replace("__ALLOWED_EMAILS__", process.argv[1]));
' "$EMAILS"

echo "Rendered: .firebaserc, pwa/firebase-config.js, firestore.rules"
